# Generated by Django 3.0.8 on 2020-09-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200905_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.BigIntegerField(),
        ),
    ]
