# Generated by Django 3.0.8 on 2020-09-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200905_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Username',
            new_name='username',
        ),
    ]
