# Generated by Django 3.0.8 on 2020-09-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onemoreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edittable',
            name='Address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='edittable',
            name='Experience',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='edittable',
            name='Location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='edittable',
            name='Profession',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='edittable',
            name='college',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='edittable',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='edittable',
            name='course',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='edittable',
            name='dob',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='edittable',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='edittable',
            name='englishlevel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='edittable',
            name='gender',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='edittable',
            name='joindate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='edittable',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='edittable',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='edittable',
            name='projects',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='edittable',
            name='resume',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='edittable',
            name='skills',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='edittable',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='edittable',
            name='year',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
